import type { Metadata } from "next";
import { Cal_Sans, Geist, Geist_Mono } from "next/font/google";
import Image from "next/image"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const calSans = Cal_Sans({
  weight: "400",
  variable: "--font-cal-sans"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
      <html
          lang="en"
          className={`${calSans.variable} h-full antialiased`}
      >

        <body className="min-h-full flex flex-col">
        <nav className="justify-between w-full bg-white h-[10vh]">
          <ul className={"flex flex-row text-[1.5rem] sm:text-[2.5rem] gap-4 md:gap-14 text-black m-8 p-4 items-center"}>
            <li>
              <a href={"#home"}>Home</a>
            </li>
            <li>
              <a href={"#iterations"}>Iterations</a>
            </li>
            <li>
              <a href={"#info"}>Info</a>
            </li>
            <li className={"ml-auto"}>
              <Image
                src={"cqlogo.svg"}
                width={150}
                height={150}
                alt={"CodeQuantum logo"}
                className="h-full w-full grow"
                />
            </li>
          </ul>
        </nav>
        {children}
        </body>
      </html>
  );
}